spring:

  datasource:
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: mesiclipboarddb
    url: "jdbc:mysql://mesiclipboarddb:3306/mesiclipboarddb?autoReconnect=true"
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate.ddl-auto: update
