spring:

#  datasource:
#    platform: mysql
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    name: mesi-io-db
#    url: "jdbc:mysql://mesi-io-db:3306/mesidb?autoReconnect=true"
#    username: root
#    password: root

  data.mongo:
    uri: 'mongodb://localhost:27017'
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate.ddl-auto: update

server:
  port: 8443

  ssl:
    key-store: classpath:keystore.p12
    key-store-type: pkcs12
    key-store-password: password
    key-password: password
    key-alias: dummy

logging:
  level:
    mesi.io: DEBUG
  file:
    name: log/mesi-io.log
