swagger: "2.0"

info:
  description: "API documentation for mesi.io"
  version: "1.0.0"
  title: "REST API for mesi.io"
  contact:
    email: "uintptr96@gmail.com"
    
host: "mesi.io"
basePath: "/api"

tags:
- name: "user"
  description: "User API"
- name: "clipboard"
  description: "Clipboard API"
  
schemes:
- "https"

paths:
            
  /clipboard:
    post:
      tags:
      - "clipboard"
      summary: "Add a new clipbord entry"
      description: "Adds a new clipboard entry. The endpoint consumes a ClipboardContent object. If the received content string is empty, no new entry will be created."
      operationId: "addClipboardEntry"
      consumes:
      - "application/json"
      parameters:
        - in: 'query'
          name: "content"
          description: "Clipboard content that should be stored"
          required: true
          type: "string"
      responses:
        201:
          description: "Created"
        400:
          description: "Missing or empty content"
          
    get:
      tags:
      - 'clipboard'
      summary: 'Retrieve all stored clipboard entries'
      description: 'This endpoint returns a list of all stored clipboard entries, orderd by timestamp desc.'
      operationId: 'getAllClipboardEntries'
      produces:
      - "application/json"
      responses:
        200:
          description: 'All clipboard entries'
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ClipboardEntry"
            
definitions:

  User:
    type: 'object'
    required: 
    - 'userName'
    - 'email'
    - 'password'
    properties:
      userName:
        type: string
      email:
        type: string
      password:
        type: string
        
  ClipboardEntry:
    type: "object"
    required: 
    - "content"
    - "timeStamp"
    properties:
      content:
        type: "string"
        example: "clipboard text"
      timeStamp:
        type: "string"
        example: "01-01-2000"