spring:
  profiles.active: prod

server:
  port: 8443

  ssl:
    key-store: classpath:lekeystore.jks
    key-store-type: pkcs12
    key-store-password: password
    key-password: password
    key-alias: lekeystore

logging:
  level:
    mesi.io: DEBUG
  file:
    name: log/mesi-io.log
