spring:
  profiles.active: prod

#server:
#  port: 8443
#
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-type: pkcs12
#    key-store-password: password
#    key-password: password
#    key-alias: dummy

logging:
  level:
    mesi.io: DEBUG
  file:
    name: log/mesi-io.log
